drop table if exists endpoint_hit;

create table endpoint_hit (
    id integer primary key generated by default as identity not null,
    app varchar (100) not null,
    uri varchar (1000) not null,
    ip varchar (20) not null,
    date_time timestamp without time zone not null
);
