version: '3.1'
services:
  stats-server:
    build: stats-service/stats-server/
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=explore

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore

  ewm-service:
    build: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=explore

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore